function cart(){return JSON.parse(localStorage.getItem('veblyss-cart')||'[]')}
function saveCart(c){localStorage.setItem('veblyss-cart',JSON.stringify(c));updateBadge()}
function addToCart(id,qty=1){const c=cart();const x=c.find(i=>i.id===id);if(x)x.qty+=qty;else c.push({id,qty});saveCart(c);toast('Added to your cart');}
function removeFromCart(id){saveCart(cart().filter(i=>i.id!==id));renderCart()}
function updateBadge(){const n=cart().reduce((s,i)=>s+i.qty,0);document.querySelectorAll('[data-cart-count]').forEach(e=>e.textContent=n)}
function toast(msg){let t=document.querySelector('.toast');if(!t){t=document.createElement('div');t.className='toast';Object.assign(t.style,{position:'fixed',right:'20px',bottom:'20px',background:'#0c5d5a',color:'#fff',padding:'14px 20px',borderRadius:'8px',zIndex:99,boxShadow:'0 10px 30px rgba(0,0,0,.2)'});document.body.appendChild(t)}t.textContent=msg;t.style.display='block';clearTimeout(window.__toast);window.__toast=setTimeout(()=>t.style.display='none',1800)}
function productCard(p){return `<article class="card"><a href="product.html?id=${p.id}"><div class="card-img"><img src="${p.img}" alt="${p.name}"></div></a><div class="card-body"><h3>${p.short}</h3><a class="view-details" href="product.html?id=${p.id}">View Details <span>→</span></a></div></article>`}
function renderProducts(target,limit){const el=document.querySelector(target);if(!el)return;el.innerHTML=PRODUCTS.slice(0,limit||PRODUCTS.length).map(productCard).join('')}
function renderProductDetail(){const q=new URLSearchParams(location.search),p=product(q.get('id'))||PRODUCTS[0];const el=document.querySelector('#product-detail');if(!el)return;el.innerHTML=`<div class="detail-image"><img src="${p.img}" alt="${p.name}"></div><div><div class="eyebrow">${p.category}</div><h1>${p.name}</h1><div class="price">₹${p.price.toLocaleString('en-IN')}</div><p>${p.desc}</p><ul class="info-list">${p.bullets.map(x=>`<li>✓ ${x}</li>`).join('')}</ul><div class="qty"><button onclick="changeQty(-1)">−</button><input id="qty" value="1" min="1" type="number"><button onclick="changeQty(1)">+</button></div><button class="btn" onclick="addToCart('${p.id}',parseInt(document.querySelector('#qty').value||1))">Add to Cart</button> <a class="btn alt" href="shop.html">Continue Shopping</a></div>`}
function changeQty(d){const i=document.querySelector('#qty');i.value=Math.max(1,(parseInt(i.value)||1)+d)}
function renderCart(){const el=document.querySelector('#cart');if(!el)return;const c=cart();if(!c.length){el.innerHTML='<div class="empty"><h2>Your cart is empty</h2><p>Explore the VeBlyss collection and add something you love.</p><a class="btn" href="shop.html">Shop Products →</a></div>';return}let total=0;el.innerHTML=c.map(i=>{const p=product(i.id);const sub=p.price*i.qty;total+=sub;return `<div class="cart-row"><img src="${p.img}" alt=""><div><strong>${p.short}</strong><div style="color:#6b7774;font-size:12px">₹${p.price.toLocaleString('en-IN')} each</div></div><div>Qty ${i.qty}</div><strong>₹${sub.toLocaleString('en-IN')}</strong><button class="remove" onclick="removeFromCart('${p.id}')">×</button></div>`}).join('')+`<div class="cart-total"><h2>Total: ₹${total.toLocaleString('en-IN')}</h2><button class="btn" onclick="checkout()">Proceed to Checkout →</button></div>`}
function checkout(){toast('Checkout will connect to Razorpay UPI in the next integration phase')}
function submitContact(e){e.preventDefault();toast('Thank you — your enquiry has been captured for this demo.');e.target.reset()}
document.addEventListener('DOMContentLoaded',()=>{updateBadge();renderProducts('#home-products',6);renderProducts('#shop-products');renderProductDetail();renderCart()});
