const PRODUCTS=[
{id:'ghee',name:'VeBlyss Amrit Gold Desi Ghee',short:'Amrit Gold Desi Ghee',price:799,img:'assets/ghee.jpg',category:'Food Essentials',desc:'A premium desi ghee crafted for everyday Indian kitchens, bringing rich flavour and traditional goodness to every meal.',bullets:['Authentic Indian food essential','Quality-focused sourcing','Suitable for everyday cooking and traditional recipes']},
{id:'coconut-oil',name:'VeBlyss CocoNara Virgin Coconut Oil',short:'Virgin Coconut Oil',price:499,img:'assets/coconut-oil.jpg',category:'Natural Oils',desc:'Cold pressed virgin coconut oil presented in a clean, premium format for cooking and everyday wellness routines.',bullets:['Cold pressed virgin coconut oil','Natural coconut goodness','Versatile everyday use']},
{id:'pooja-oil',name:'VeBlyss Pancha Jyothi Pooja Oil',short:'Pooja Oil',price:299,img:'assets/pooja-oil.jpg',category:'Devotional Essentials',desc:'A traditional blend created for lamps, prayers and devotional practices, presented with clear product information.',bullets:['Traditional five-oil blend','For lamps and devotional use','Made in India']},
{id:'wallet',name:"VeBlyss Men's Leather Wallet",short:"Men's Leather Wallet",price:899,img:'assets/wallet.jpg',category:'Lifestyle',desc:'A classic brown leather wallet designed around practical everyday carry with a subtle VeBlyss mark.',bullets:['Classic everyday design','Multiple card and cash sections','Premium leather look']},
{id:'copper-bottles',name:'VeBlyss Copper Bottles',short:'Copper Bottles',price:699,img:'assets/copper-bottles.jpg',category:'Home & Lifestyle',desc:'A curated range of copper bottle styles combining Indian material heritage with contemporary everyday use.',bullets:['Multiple styles available','Traditional copper aesthetic','Reusable everyday bottle']},
{id:'beer-mug',name:'VeBlyss Beer Mug',short:'Beer Mug',price:599,img:'assets/beer-mug.png',category:'Home & Lifestyle',desc:'A distinctive wood-and-metal style beer mug that brings a crafted, conversation-starting character to your barware.',bullets:['Distinctive crafted look','Comfortable handle','Ideal for home barware']}
];
function product(id){return PRODUCTS.find(p=>p.id===id)}
